GestaoVendasCompleto-Com-Grafico-em-M.V.C/Controllers/VendedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models; // Importado

namespace SistemaVendas.Controllers
{
    public class VendedorController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ListaVendedores = new VendedorModel().ListarTodosVendedores();
            return View();
        }

        [HttpGet]
        public IActionResult Cadastro(int? Id)
        {
            if (Id !=null)
            {
                // Carregar o registro do vendedor numa ViewBag
                ViewBag.Vendedor = new VendedorModel().RetornarVendedor(Id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(VendedorModel vendedor)
        {
            if (ModelState.IsValid)
            {
                vendedor.Gravar();
                return RedirectToAction("Index");
            }
            return View();
        }

        // Excluir Registro
        public IActionResult Excluir(int Id)
        {
            ViewData["IdExcluir"] = Id;
            return View();
        }

        public IActionResult ExcluirVendedor(int Id)
        {
            {
                // Tratamento para que se o Vendedor não estiver vinculado a uma venda Exclui
                // Se Caso não, Não Exclui... Redireciona para View (Tratamento).
                try
                {
                    new VendedorModel().Excluir(Id);
                    return View();
                }
                catch (Exception)
                {
                    return View("Tratamento");
                }
            }
        }
    }
}

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Vendedor/Cadastro.cshtml
<!-- Inportar:-->
@model VendedorModel
@{ 
    Layout = null;
}

<script>
    function Voltar() {
        window.location.href = '../../Vendedor/Index';
    }
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true"></span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Cadastro de Vendedores</h4>
        </div>
        <div class="modal-body">
            

            <form asp-controller="Vendedor" asp-action="Cadastro">
                <input type="hidden" asp-for="Id" value="@try { @ViewBag.Vendedor.Id } catch { }" />

                <div class="form-group">
                    <label>Nome</label>
                    <input asp-for="Nome" type="text" class="form-control" required value="@try { @ViewBag.Vendedor.Nome } catch { }" />
                </div>


                <div class="form-group">
                    <label>E-Mail</label>
                    <input asp-for="Email" type="text" class="form-control" required value="@try { @ViewBag.Vendedor.Email } catch { }" />
                </div>

                <button type="submit" class="btn-success btn-sm"><i class="fa fa-user"></i> Registrar</button>
                <button style="margin-left: 3px;" type="button" class="btn  btn-info btn-sm" onclick="Voltar()"><i class="fa fa-step-backward"></i> Retornar para Listagem de Vendedores</button>

            </form>


        </div>        
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Vendedor/Excluir.cshtml
@{
    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Exclusão</h4>
        </div>
        <div class="modal-body">
            <h3>Deseja Realmente Excluir o Registro Selecionado ?</h3>
            <hr />

            <div class="form-inline">
                <button type="button" class="btn btn-danger btn-sm" onclick="Nao()"><i class="fa fa-check"></i> Não</button>
                <button type="button" class="btn btn-success btn-sm Cadastro" onclick="Sim()"><i class="fa fa-check"></i> Sim</button>
            </div>
        </div>
    </div>

</div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    function Sim()
    {
        window.location.href = '../../Vendedor/ExcluirVendedor/' + '@ViewData["IdExcluir"].ToString()';
    }

    function Nao()
    {
        window.location.href = '../../Vendedor/Index'
    }
</script>

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Vendedor/ExcluirVendedor.cshtml
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true"></span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Sucesso !!!</h4>
        </div>
        <div class="modal-body">
            <div class="container">
                <h3>Registro Exluido com Sucesso !</h3>
                <hr />
                <br />
                <button type="button" class="btn btn-info" onclick="Voltar()"> <i class="fa fa-step-backward"></i> Voltar à Listagem de Clientes</button>
            </div>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>

    function Voltar() {
        window.location.href = '../../Vendedor/Index'
    }

</script>

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Vendedor/Filtro.cshtml
@model VendedorModel

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<br />
<div class="container">
    <div class="row">
        <div class="col col-2">
            <h3 style="margin-left: 15px;">Filtro</h3>
        </div>
        <br />

        <form asp-controller="Vendedor" asp-action="Filtro">

            <div class=" col-lg-2">
                <input asp-for="Id" type="number" class="form-control" placeholder="Código" />
            </div>
            <div class="col col-lg-8">
                <button type="submit" class="btn btn-default"><i class="fa fa-check"></i> Buscar</button>
            </div>

        </form>
    </div>
</div>

<br />

<div class=" container">
    <div class="table-responsive">
        <table class=" table-bordered">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th style="padding: 0px 20px 0px 20px;">Id</th>
                    <th style="padding: 0px 20px 0px 20px;">Nome</th>
                    <th style="padding: 0px 20px 0px 20px;">Email</th>
                </tr>
            </thead>

            <tbody>

                @{
                    try
                    {
                        foreach (var item in (List<VendedorModel>)ViewBag.ListaVendedor)
                        {
                            <tr>
                                <td style="padding:2PX;"><button type="button" class="btn btn-warning btn-sm Editar" data-id="@item.Id"><i class="fa fa-edit"></i> Editar</button></td>
                                <td style="padding:2PX;"><button type="button" class="btn btn-danger btn-sm Excluir" data-id="@item.Id"><i class="fa fa-eraser"></i> Excluir</button></td>

                                <td style="padding: 0px 20px 0px 20px;">@item.Id</td>
                                <td style="padding: 0px 20px 0px 20px;">@item.Nome</td>
                                <td style="padding: 0px 20px 0px 20px;">@item.Email</td>
                            </tr>
                        }
                    }
                    catch { }
                }
            </tbody>
        </table>
        <div class="modal" id="modal">

        </div>

        @section scripts{
            <script>
                $(function () {
                    $(".Editar").click(function () {
                        var id = $(this).attr("data-id");
                        $("#modal").load("Cadastro?id=" + id, function () {
                            $("#modal").modal();
                        })
                    });
                })

                $(function () {
                    $(".Excluir").click(function () {
                        var id = $(this).attr("data-id");
                        $("#modal").load("Excluir?id=" + id, function () {
                            $("#modal").modal();
                        })
                    });
                })

            </script>
        }

    </div>
</div>

<br />

<br />
<script>
    // Função em JS para Editar
    function Editar(Id) {
        window.location.href = "../Vendedor/Cadastro/" + Id;
    }

    // Função em JS para Excluir
    function Excluir(Id) {
        window.location.href = "../Vendedor/Excluir/" + Id;
    }
</script>

<!-- Rotina Abaixo é para voltar a Listagem de Produtos -->
<button style="margin-left: 15px;" type="button" class="btn  btn-default btn-sm" onclick="Voltar()"><i class="fa fa-step-backward"></i> Retornar para o Menu</button>

<script>
    function Voltar() {
        window.location.href = '../../Home/Menu';
    }
</script>

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Vendedor/Index.cshtml
<div class="container">
    <br />
    <br />
    <div class="row'">
        <div class="col col-lg-5">
            <h3>Lista de Vendedores</h3>
            <br />
        </div>
        <div class="col col-sm-7">
            <button style="margin: 12px;" type="button" class="btn btn-default" onclick="Filtro()"><i class="fa fa-filter"></i> Filtro por Código</button>
        </div>
    </div>
</div>


<div class=" container">
    <div class="table-responsive">
        <table class=" table-bordered">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th style="padding: 0px 20px 0px 20px;">Id</th>
                    <th style="padding: 0px 20px 0px 20px;">Nome</th>
                    <th style="padding: 0px 20px 0px 20px;">Email</th>
                </tr>
            </thead>

            <tbody>

                @{
                    foreach (var item in (List<VendedorModel>)ViewBag.ListaVendedores)
                    {
                        <tr>
                            <td style="padding:2PX;"><button type="button" class="btn btn-warning btn-sm Editar" data-id="@item.Id"><i class="fa fa-edit"></i> Editar</button></td>
                            <td style="padding:2PX;"><button type="button" class="btn btn-danger btn-sm Excluir" data-id="@item.Id"><i class="fa fa-eraser"></i> Excluir</button></td>

                            <td style="padding: 0px 20px 0px 20px;">@item.Id</td>
                            <td style="padding: 0px 20px 0px 20px;">@item.Nome</td>
                            <td style="padding: 0px 20px 0px 20px;">@item.Email</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <div class="modal" id="modal">

        </div>

        @section scripts{
            <script>
                $(function () {
                    $(".Editar").click(function () {
                        var id = $(this).attr("data-id");
                        $("#modal").load("Cadastro?id=" + id, function () {
                            $("#modal").modal();
                        })
                    });
                })

                $(function () {
                    $(".Excluir").click(function () {
                        var id = $(this).attr("data-id");
                        $("#modal").load("Excluir?id=" + id, function () {
                            $("#modal").modal();
                        })
                    });
                })

                $(".Cadastro").click(function () {
                    $("#modal").load("Cadastro", function () {
                        $("#modal").modal();
                    })
                });

            </script>
        }
    </div>
    <br />
    <button class="btn  btn-success btn-sm Cadastro" type="button"> <i class="fa fa-user"></i> Cadastrar Vendedor</button>
    <button style="margin-left: 3px;" type="button" class="btn  btn-default btn-sm" onclick="Voltar()"><i class="fa fa-step-backward"></i> Retornar para o Menu</button>

</div>

<script>

    function Filtro() {
        window.location.href = "../Vendedor/Filtro"
    }

    function Voltar() {
        window.location.href = '../../Home/Menu';
    }
</script>

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Vendedor/Tratamento.cshtml
<!-- Inportar:-->
@model VendedorModel

<br />
<br />
<h1><em>Você não pode EXCLUIR este Vendedor !!!</em></h1>
<br/>
<h4><em style="color:darkred;">Este Vendedor não pode ser excluido por motivo de que existe(m) Venda(s) Registrada(s) para o mesmo.</em></h4>
<br /> 
<button type="button" class="btn  btn-primary" onclick="Voltar()">Retornar à Lista de Vendedores</button>

<script>

    function Voltar() {
        window.location.href = '../../Vendedor/Index';
    }
</script>