GestaoVendasCompleto-Com-Grafico-em-M.V.C/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http; // Importado
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models; // Importado

namespace SistemaVendas.Controllers
{
    public class VendaController : Controller
    {
        private IHttpContextAccessor httpContext;

        // Recebe o Contexto HTTP via Injeção de Dependência
        public VendaController(IHttpContextAccessor HttpContextAccessor)
        {
            httpContext = HttpContextAccessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.ListaVendas = new VendaModel().ListagemVendas();
            return View();
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            CarregarDados();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(VendaModel venda)
        {
            // Captura o Id do Vendedor Logado no Sistema para direcionar a venda ao mesmo.
            venda.Vendedor_Id = httpContext.HttpContext.Session.GetString("IdUsuarioLogado");
            if (ModelState.IsValid)
            {
                venda.Inserir();
                CarregarDados();
                return RedirectToAction("Index");
            }
            else
            {
                // View Criada apenas para tratar Reg. de Venda.
                return View ("Tratamento"); 
            }
        }           
        
        private void CarregarDados()
        {
            ViewBag.ListaClientes = new VendaModel().RetornarListaClientes();
            ViewBag.ListaVendedores = new VendaModel().RetornarListaVendedores();
            ViewBag.ListaProdutos = new VendaModel().RetornarListaProdutos();
        }
    }
}

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Venda/Index.cshtml
<br />
<br />
<h2>Listagem de Vendas</h2>

<br />

<table class="table table-bordered">
    <thead>
        <tr>

            <th>Id</th>
            <th>Data</th>
            <th>Vendedor</th>
            <th>Cliente</th>
            <th>Total</th>
        </tr>
    </thead>

    <tbody>

        @{
            foreach (var item in (List<VendaModel>)ViewBag.ListaVendas)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Data</td>
                    <td>@item.Vendedor_Id</td>
                    <td>@item.Cliente_Id</td>
                    <td>R$ @item.Total</td>
                </tr>
            }
        }
    </tbody>
</table>
<div class="modal" id="modal">

</div>

@section scripts{
    <script>
       
        $(".Venda").click(function () {
            $("#modal").load("Registrar", function () {
                $("#modal").modal();
            })
        });

    </script>
}
<br />
<button class="btn  btn-success btn-sm Venda" type="button"> <i class="fa fa-check"></i> Registrar Nova Venda</button>
<button style="margin-left: 3px;" type="button" class="btn  btn-default btn-sm" onclick="Voltar()"><i class="fa fa-step-backward"></i> Retornar para o Menu</button>

<script>

    function Voltar() {
        window.location.href = '../../Home/Menu';
    }
</script>

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Venda/Registrar.cshtml
<!-- Inportar:-->
@model VendaModel
@{
    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true"></span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Registrar Uma Venda</h4>
        </div>
        <div class="modal-body">
            <form asp-controller="Venda" asp-action="Registrar">
                @*<input type="hidden" asp-for="Id" value="@try { @ViewBag.Venda.Id } catch { }" />*@

                <div class="form-group">
                    <label>Cliente</label>
                    <select asp-for="Cliente_Id" class="form-control">
                        @{
                            try
                            {
                                foreach (var item in (List<ClienteModel>)ViewBag.ListaClientes)
                                {
                                    <option value="@item.Id">@item.Nome</option>
                                }
                            }
                            catch (Exception)
                            {
                                //
                            }
                        }
                    </select>
                </div>

                <!-- Vendedores esta sendo pego na Classe pelo Id Logado, não fazendo sendido ser apresentado aqui -->
                <!--===============================================================================================-->
                @*<div class="form-group">
                        <label>Vendedor</label>
                        <select asp-for="Vendedor_Id" class="form-control">
                            @{
                                foreach (var item in (List<VendedorModel>)ViewBag.ListaVendedores)
                                {
                                    <option value="@item.Id">@item.Nome</option>
                                }
                            }
                        </select>
                    </div>*@


                <label style="color:blue;">Produtos</label>
                <br />
                <div class="form-group">
                    <div class="col-lg-7">
                        <select style="margin-left: -16px;" class="form-control" id="sltProduto">
                            @{
                                try
                                {
                                    foreach (var item in (List<ProdutoModel>)ViewBag.ListaProdutos)
                                    {
                                        <option value="@item.Id">@item.Nome | @item.Preco_Unitario</option>
                                    }
                                }
                                catch (Exception)
                                {
                                    //
                                }
                            }
                        </select>
                    </div>
                    <div class="col-lg-2">
                        <input type="text" class="form-control" value="1" id="txtQuantidade" required /> <!-- 1 Valor Defoult -->
                    </div>

                    <div class="col-lg-3">
                        <button type="button" class="btn btn-block btn-warning" onclick="AdicionarProduto()"><i class="fa fa-plus-circle"></i> Adicionar</button>
                    </div>
                </div>

                <br /><br />

                <table class="table table-bordered">

                    <thead>
                        <tr>
                            <td>Id</td>
                            <td>Nome</td>
                            <td>Quantidade</td>
                            <td>Preço Unitário</td>
                            <td>Total</td>
                        </tr>
                    </thead>
                    <tbody id="listaProdutos"></tbody>
                </table>

                <div style="float:left; font-size:22px;">Total: R$</div>
                <div style="float:left; font-size:22px; margin-left:5px;" id="divTotal">0.00</div>

                <input type="hidden" id="txtTotal" asp-for="Total" />

                <br /><br />

                <!--No style, para aparecer o JSON que vai ser lançado, colocar (Display: inline;-->
                <textarea asp-for="ListaProdutos" id="ListaProdutosJSON" style="display:none;"></textarea>

                <button class="btn  btn-success btn-sm" type="submit" onclick="Cadastrar()"> <i class="fa fa-check"></i> Registrar Venda</button>
                <button style="margin-left: 3px;" type="button" class="btn  btn-default btn-sm" onclick="Voltar()"><i class="fa fa-step-backward"></i> Retornar para o</button>

            </form>
        </div>

    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>

    var Itens = Object();
    Itens.Produtos = new Array();

    var CodigoProduto = document.getElementById("sltProduto");
    var QtdeProduto = document.getElementById("txtQuantidade");
    var ListaProdutos = document.getElementById("listaProdutos");
    var TotalVenda = document.getElementById("divTotal");
    var txtTotal = document.getElementById("txtTotal");
    var ListaProdutosJSON = document.getElementById("ListaProdutosJSON");

    function Voltar() {
        window.location.href = '../Venda/Index';
    }

    function AdicionarProduto() {
        var DescricaoPreco = CodigoProduto.options[CodigoProduto.selectedIndex].text;
        var arrayDescricaoPreco = DescricaoPreco.split('|');
        var total = (arrayDescricaoPreco[1].replace(",", ".") * QtdeProduto.value);
        total = Math.round(total * 100) / 100;

        Itens.Produtos.push({
            "CodigoProduto": CodigoProduto.value,
            "DescricaoProduto": arrayDescricaoPreco[0],
            "QtdeProduto": QtdeProduto.value,
            "PrecoUnitario": arrayDescricaoPreco[1],
            "Total": total
        });

        ListaProdutosJSON.innerHTML = JSON.stringify(Itens.Produtos); // Pega o Json e joga numa TextArea Invisível.

        var produto = "<tr>" +
            "<td>" + CodigoProduto.value + "</td>" +
            "<td>" + arrayDescricaoPreco[0] + "</td>" +
            "<td>" + QtdeProduto.value + "</td>" +
            "<td> R$" + arrayDescricaoPreco[1] + "</td>" +
            "<td> R$ " + total + "</td>" +
            "</tr>";

        ListaProdutos.innerHTML += produto;
        var totalGeral = Math.round((TotalVenda.innerText * 1 + total) * 100) / 100;
        TotalVenda.innerHTML = totalGeral;
        txtTotal.value = totalGeral.toString().replace(".", ",");
    }

</script>

GestaoVendasCompleto-Com-Grafico-em-M.V.C/Views/Venda/Tratamento.cshtml
<!-- Inportar:-->
@model VendaModel

<br />
<br />
<div class=" container">
    <div class="table-responsive">
        <h1 style="color:darkred;"><em>Você não selecionou nenhum produto para venda !!!</em></h1>
        <h4 style="color:darkred;"><em>Vide botão em destaque.</em></h4>
        <hr />
        <img src="~/images/FotoTratamento.png" width="850" height="300" />
        <br /><br />
    </div>
</div>
<hr/>
<button type="button" class="btn  btn-primary" onclick="Voltar()"><i class="fa fa-step-backward"></i> Retornar ao Registro de Vendas</button>

<script>

    function Voltar() {
        window.location.href = '../Venda/Index';
    }
</script>